version: '3'
services:
  streamset:
    image: alextanhongpin/streamsets:1.1.4
    ports:
    - 18630:18630
    volumes:
    - ./data/streamsets:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.6.14-management
    hostname: rabbit1
    environment:
    - RABBITMQ_ERLANG_COOKIE=123456
    - RABBITMQ_DEFAULT_USER=rabbitmq
    - RABBITMQ_DEFAULT_PASS=rabbitmq
    - RABBITMQ_DEFAULT_VHOST=/
    ports:
    - 15672:15672
    - 5672:5672
